// you would define your config files here!

module.exports = {
    routes:[
        {
            path:'./html/index',
            methods:['GET'],
        },
        {
            path:'./html/login',
            methods:['GET'],
        },
        {
            path:'./html/books',
            methods:['GET'],
        },
        {
            path:'./api/books',
            methods:['GET','POST'],
        },
        {
            path:'./api/books/:id',
            methods:['GET','DELETE'],
        },
        {
            path:'./api/books/volumes',
            methods:['GET','POST'],
        },
        {
            path:'./api/books/volumes/:id',
            methods:['GET','DELETE'],
        },
        {
            path:'./api/magazines',
            methods:['GET','POST'],
        },
        {
            path:'./api/magazines/:id',
            methods:['DELETE','GET','PATCH'],
        },
        {
            path:'./app/calculate',
            methods:['GET'],
        },
        {
            path:'./app/calculate/:id',
            methods:['GET','PUT','PATCH'],
        },
        {
            path:'./app/signup/members/:id',
            methods:['GET','PUT','PATCH'],
        },
        {
            path:'./app/signup/new/vip',
            methods:['GET','POST'],
        },
    ]
}
